# Generated by Django 4.0.6 on 2022-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_engnews_runews'),
    ]

    operations = [
        migrations.AddField(
            model_name='runews',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
