# Generated by Django 4.0.6 on 2022-08-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_runews_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='engnews',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='engnews',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='engnews',
            name='date',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='runews',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='runews',
            name='date',
            field=models.JSONField(null=True),
        ),
    ]
