# Generated by Django 4.0.6 on 2022-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_engnews_pic_alter_runews_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='engnews',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runews',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
